# Generated by Django 4.2.8 on 2023-12-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('montant_total', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nom_ar', models.CharField(max_length=50)),
                ('prenom_ar', models.CharField(max_length=50)),
                ('date_naiss', models.DateField(null=True)),
                ('sexe', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=12)),
                ('grade', models.CharField(max_length=12)),
                ('salaire', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naiss', models.DateField(null=True)),
                ('sexe', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=12)),
                ('montant_total', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naiss', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, max_length=50, null=True)),
                ('NNI', models.BigIntegerField(blank=True, null=True)),
                ('RIM', models.CharField(blank=True, max_length=20, null=True)),
                ('date_inscription', models.DateField(blank=True, null=True)),
                ('numero_absence', models.IntegerField(blank=True, default=0)),
                ('frais_mensuels', models.IntegerField(blank=True, default=0, null=True)),
                ('id_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('coefficient', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('coefficient', models.CharField(max_length=50)),
                ('note_complete', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('annee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile2', models.CharField(blank=True, max_length=12, null=True)),
                ('date_inscription', models.DateField(blank=True, null=True)),
                ('frais_mensuels', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('montant_total', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('pourcentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('day', models.CharField(max_length=50)),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.class')),
                ('id_ens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.enseignant')),
                ('id_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointage', models.IntegerField(blank=True, null=True)),
                ('salaire', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('id_ens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret', models.IntegerField(blank=True, null=True)),
                ('pay', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('id_partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.partenaire')),
            ],
        ),
        migrations.CreateModel(
            name='ParentmoisPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.DateField(blank=True, null=True)),
                ('montant_paye', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay', models.BooleanField(default=False)),
                ('id_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.parent')),
                ('mois_paye', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.mois')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('type', models.CharField(blank=True, max_length=50)),
                ('id_etud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.etudiant')),
                ('id_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.evaluation')),
                ('id_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=50, null=True)),
                ('id_etud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.etudiant')),
                ('id_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant_evaluaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('range', models.IntegerField(blank=True, default=0, null=True)),
                ('id_etud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.etudiant')),
                ('id_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.evaluation')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='id_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.parent'),
        ),
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.class')),
                ('id_ens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.enseignant')),
                ('id_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.matiere')),
            ],
        ),
    ]
